// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1rZ3AUkdTJSVcQ_YJlqFsPw1jCo5L5uw',
    appId: '1:663587863288:web:7a305fee65c25c838a590d',
    messagingSenderId: '663587863288',
    projectId: 'praktik-ppb',
    authDomain: 'praktik-ppb.firebaseapp.com',
    storageBucket: 'praktik-ppb.appspot.com',
    measurementId: 'G-N3F0X3DSDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo80ZtvuVnTfg6qUYbqf9Uksu47aOkwak',
    appId: '1:663587863288:android:9eb32eb2bbbe5fb68a590d',
    messagingSenderId: '663587863288',
    projectId: 'praktik-ppb',
    storageBucket: 'praktik-ppb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_p-n37nBZlr9rj0Tp_yfgii90gkcBKos',
    appId: '1:663587863288:ios:239de3c9ef55eacb8a590d',
    messagingSenderId: '663587863288',
    projectId: 'praktik-ppb',
    storageBucket: 'praktik-ppb.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_p-n37nBZlr9rj0Tp_yfgii90gkcBKos',
    appId: '1:663587863288:ios:239de3c9ef55eacb8a590d',
    messagingSenderId: '663587863288',
    projectId: 'praktik-ppb',
    storageBucket: 'praktik-ppb.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1rZ3AUkdTJSVcQ_YJlqFsPw1jCo5L5uw',
    appId: '1:663587863288:web:aad429e6e8eed2c98a590d',
    messagingSenderId: '663587863288',
    projectId: 'praktik-ppb',
    authDomain: 'praktik-ppb.firebaseapp.com',
    storageBucket: 'praktik-ppb.appspot.com',
    measurementId: 'G-NC2EC1GD5Q',
  );
}
